### PR TITLE
added the size in bytes and kilobytes to "files" elements

### PR DESCRIPTION
**Pull request by schuif**
Hello,

(I have fixed build errors)

I added the size in bytes and kilobytes to every element in "files"

thanks.

(sorry for the bad english)

### CODE REVIEW

**Comment by richardgirges** [comment]
@schuif this looks good. Can you update the documentation and add a test?

**Comment by schuif** [comment]
@richardgirges ... an update for all recent merge ???

**Comment by richardgirges** [comment]
@schuif simply update the README.md file to reflect the new properties that you've introduced. And add a unit test :)

**Comment by datnguyencse** [comment]
@richardgirges will you merge this pull request, look like @schuif won't add any change. Add the size to files is very useful.

**Comment by alisherafat01** [comment]
is that merged?
can we use this feature?
what happened?

**Comment by richardgirges** [comment]
@alisherafat01 the PR didn't contain any documentation or unit tests. It's a very simple change, I would be happy to take another PR from someone else as this one is pretty outdated.

**Comment by RomanBurunkov** [comment]
Uploaded file size support added with #126 .

**Pull request closed without merging**
