### PR TITLE
Handle 'limit' event when file is over fileSize

### LINKED ISSUE #40: limit fileSize
I'm not able to detect when a file has reached the limit specified by the options when the fileupload object is created.
The module runs the next() but without any message that the file have reached the max fileSize but the file is saved truncated.
Maybe a new field truncated can be added to req.file, indicating that the file has been truncated and it has exceeded the maxFileSIze.

### PR DESCRIPTION
**Pull request by Haggus**
When 'limit' event fires, it returns 413 (Payload Too Large). Let me know if there is anything you'd like to do differently :)

This should close #40

### CODE REVIEW

**Comment by richardgirges** [comment]
Hi @Haggus thanks for the PR! It looks good - would you mind adding a unit test for this update? 

Cheers

**Comment by Haggus** [comment]
Here you go! :)

**Comment by ShakMR** [comment]
Why not, instead of ending the request, adding some kind of attribute to the file (`limitReached = true` or `truncated == true`) to let us know so we can handle the error in our side?

**Comment by richardgirges** [comment]
I do like the idea of allowing the error to be handled by the user. What do you think @Haggus ?

@ShakMR since you already coded it, would you mind sending a PR?

I wonder if there would also be value in providing the user with _either_ option. If we go with that, we can create a new configuration option and merge both solutions in.

**Comment by Haggus** [comment]
I think a configuration option to turn on automatic throw would be the best solution here.

Personally I prefer that the lib throws an error as soon as it hits the limit, but as @ShakMR mentioned, this might not be what everyone wants. 

Also, when it comes to `truncated` flag, I think busboy may already have this implemented.

**Comment by tianjianchn** [comment]
Maybe trying these codes below:
```js
.on('limit', () => {
  const err = new Error('Request Entity Too Large');
  err.statusCode = 413;
  next(err);
});
```

Since express can handle this error and respond right status code(413). and if user wants to handle that exception, he can use custom `next` function.
Hope it helps.

**Pull request merged**
