### PR TITLE
Add numFilesLimitHandler option for handling busboy's number of files limit event

### PR DESCRIPTION
**Pull request by jseppi**
- Adds `numFilesLimitHandler` option
- Fixes various broken tests

### CODE REVIEW

**Comment by jseppi** [comment]
cc @richardgirges

**Comment by jseppi** [comment]
Passing Travis build: https://travis-ci.org/richardgirges/express-fileupload/builds/546420310

**Comment by RomanBurunkov** [comment]
Hi,

Not sure why added additional dependency: mkdirp.

**Comment by jseppi** [comment]
@RomanBurunkov because the `{recursive: true}` option for `fs.mkdir` is not supported in many versions of Node. It was not added until Node `10.12.0` (see [changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#2018-10-10-version-10120-current-targos)). That is why the test for the recursive `checkAndMakeDir` was failing on Travis (such as [here](https://travis-ci.org/richardgirges/express-fileupload/jobs/542696040#L699)).

[`mkdirp`](https://github.com/substack/node-mkdirp) is a well-tested, very popular module that can recursively make directories.

**Comment by closingin** [comment]
Hi @jseppi , shouldn't the fix for the tests be in a separate PR ?

Anyway, now that it's there, I guess it's fine ! Thanks for fixing it though (I'm the guy who added the option), it's true that I didn't think of older node versions, mb.

**Pull request closed without merging**
