### PR TITLE
#51 Parsing nested objects

### PR DESCRIPTION
**Pull request by JamesHemery**
Fix issue #51 

Creating processNested.js, that expose a function will convert flatten object to nested object. 
Transform req.body with this function in finish busboy event.

What do you think about this ?

Thanks,

### CODE REVIEW

**Comment by richardgirges** [comment]
@JamesHemery  looks great! I'm wondering if maybe we should make it optional? i.e. allow a user to turn the feature on (i.e. like these options: https://github.com/richardgirges/express-fileupload#available-options)

What do you think?

**Comment by JamesHemery** [comment]
@richardgirges Thanks for your feedback. Yes I think it's better to offer it as an option, now the question is whether it's enabled by default or not?

I would make this optional tomorrow. I still have to apply the nested filter on the req.files object, I had forgotten.

Also, what do you think of adding an option to unite req.files and req.body? i.e. add files within req.body

Thanks,

**Comment by JamesHemery** [comment]
@richardgirges So, I added the parseNested option, which is disabled by default so as not to break existing integrations. I wrote the unit test for this option, but not yet with the file upload.

The nested filter now applies to req.files as well. It should therefore write the unit test with the file upload.

**Comment by richardgirges** [comment]
Awesome thanks @JamesHemery ! I'm merging this in today

**Comment by richardgirges** [comment]
Released to NPM:  https://github.com/richardgirges/express-fileupload/releases/tag/v1.1.1-alpha.1

**Pull request merged**
