### PR TITLE
Feat: Custom logger

### PR DESCRIPTION
**Pull request by RobinTail**
I'm using `express-fileupload` for an application having more advanced loggers than `Console`.
I'd like to suggest the feature that enables consumers to configure the logger while preserving the `console` by default.

### CODE REVIEW

**Comment by RobinTail** [comment]
@richardgirges , please review

**Comment by RomanBurunkov** [comment]
Hi @RobinTail 

Thank u for this PR.
Just one suggestion:
What if you add `console` to the defaults, and remove OR in logging function.
If it's ok, I will be happy to merge and publish it.

**Comment by RobinTail** [comment]
I can do that, but it will also require me to update some existing tests of `debugLog()` utility, @RomanBurunkov 
I will let you know once it's done.

**Comment by RobinTail** [comment]
Done, @RomanBurunkov .
I made `logger` option to be `console` by default and removed OR from `debugLog()`.
Instead, I added an additional check for the presence of the `logger` property, because of the tests that call that method directly. Those I updated as well.

**Comment by RobinTail** [comment]
@RomanBurunkov , please review again.

**Comment by RobinTail** [comment]
Types updating PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69016
FYI, @RomanBurunkov

**Pull request merged**
