### PR TITLE
Reusable file object

### PR DESCRIPTION
**Pull request by Shudrum**
Hello there!

First of all: thank you for this project! Life & time saver.

I am using this middleware on several projects, and I have, on all of those project, the same problem:

> How can I correctly test my file uploading system?

The problem is:
I do not only upload files, but I also do some business transformation on them. As I try to keep everything as simple as possible: I just use your file object without decorator or anything else.

So, for the tests… it need many boilerplates or… a decorator…

This is why this pull request:

I would love to have a real FileObject / File or just a factory. I choose the factory option to keep this project also simple.

The steps are split on several commits. If you agree on the principe, I would like to talk about the last one: https://github.com/richardgirges/express-fileupload/commit/64ff2b5b7b6bea56349ffe4eb01cb1f4c572bd83

I've exposed the `fileFactory`, so people who want to use it can simply do:

```javascript
const fileFactory = require('express-fileupload').fileFactory;
```

If you just want to replace it by:

```javascript
const fileFactory = require('express-fileupload/lib/fileFactory');
```

Just ask.

To finish, as it is quite like a _low level_ functionality, I don't think it should be documented, people who want to test it can find it easily by looking at this repository.

Thank you!

### CODE REVIEW

**Comment by r3wt** [comment]
this is awesome. great work @Shudrum

**Comment by Shudrum** [comment]
Thank you :relaxed:

**Comment by richardgirges** [comment]
NICE! Give me a day or two to digest this, I may have some questions. But I agree with the direction and need for this! It'll help me out too for testing.

**Comment by Shudrum** [comment]
You're welcome!

**Pull request merged**
