### PR TITLE
fix:temp file write timing issue

### PR DESCRIPTION
**Pull request by somewind**
#184 use promise to fix this bug

### CODE REVIEW

**Comment by RomanBurunkov** [comment]
Hi @somewind ,

Thanks for this PR.
One thought I have about this: Have you considered to check whether the file has been flushed in mv function, instead of waiting resolving of all promises? In this case we don't need req.waits at all.

**Comment by somewind** [comment]
> Hi @somewind ,
> 
> Thanks for this PR.
> One thought I have about this: Have you considered to check whether the file has been flushed in mv function, instead of waiting resolving of all promises? In this case we don't need req.waits at all.

Delay waiting, which is a good idea, but I think writing file is fast. If you move the logic to mv, does it add complexity to the code?

**Comment by RomanBurunkov** [comment]
I mean wait for resolving finish promise in mv method instead of waiting resolving all promises after busboy finish event triggered. In such case we don't need waits array and all code stuff which mange waits array. Hope that clarify my idea.

**Comment by somewind** [comment]
> I mean wait for resolving finish promise in mv method individually instead of waiting resolving all promises after busboy finish event triggered. In such case we don't need waits array and all code stuff which mange waits array. Hope that clarify my idea.

ok

**Comment by richardgirges** [comment]
This looks good to me @RomanBurunkov - I'm going to merge by EOD unless you have any reservations.

**Comment by somewind** [comment]
> I mean wait for resolving finish promise in mv method individually instead of waiting resolving all promises after busboy finish event triggered. In such case we don't need waits array and all code stuff which mange waits array. Hope that clarify my idea.

I have modified it as you said, please check the PR again, or if you have any other suggestions 😃

**Comment by RomanBurunkov** [comment]
> > I mean wait for resolving finish promise in mv method individually instead of waiting resolving all promises after busboy finish event triggered. In such case we don't need waits array and all code stuff which mange waits array. Hope that clarify my idea.
> 
> I have modified it as you said, please check the PR again, or if you have any other suggestions 😃

Yeap, I've seen that.
Probably my idea wasn't so good, since in case you need to do something with temp file before moving it u still have a chance to face with this issue.

**Comment by somewind** [comment]
> > > I mean wait for resolving finish promise in mv method individually instead of waiting resolving all promises after busboy finish event triggered. In such case we don't need waits array and all code stuff which mange waits array. Hope that clarify my idea.
> > 
> > 
> > I have modified it as you said, please check the PR again, or if you have any other suggestions 😃
> 
> Yeap, I've seen that.
> Probably my idea wasn't so good, since in case you need to do something with temp file before moving it u still have a chance to face with this issue.

How about making 'writePromise' available to the user. 

You can use  `req.files.foo.tempFileWritePromise` to wait, if you need to do something other than `req.files.foo.mv` with the temporary file

**Comment by RomanBurunkov** [comment]
@somewind 

Cool idea, but looks too complicated to use.
Don't u mind to rollback this PR to the previous version with an array of uploads, looks that is the best option for now and I'm going to merge it.

**Comment by somewind** [comment]
> @somewind
> 
> Cool idea, but looks too complicated to use.
> Don't u mind to rollback this PR to the previous version with an array of uploads, looks that is the best option for now and I'm going to merge it.

OK, understand.

**Pull request merged**
